apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dystopian-frontend
  namespace: dystopian
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dn.lsx.li
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dystopian-frontend
            port:
              number: 80
  tls:
  - hosts:
    - dn.lsx.li
    secretName: dystopian-frontend-tls
