apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: dystopian
  annotations:
    # ——— TLS & cert-manager ———
    cert-manager.io/cluster-issuer: letsencrypt-prod

    # ——— Redirecionar todo HTTP para HTTPS ———
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    # (opcional) comprime respostas
    nginx.ingress.kubernetes.io/use-gzip: "true"

spec:
  ingressClassName: ingress-nginx      
  rules:
  - host: dn.lsx.li
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dystopian-frontend
            port:
              number: 80            # porta exposta no Service
  tls:
  - hosts:
    - dn.lsx.li
    secretName: dn-lsx-li-tls       # será preenchido automaticamente pelo cert-manager
