apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dystopian

resources:
- namespace.yaml
- backend/deployment.yaml
- backend/service.yaml
- frontend/deployment.yaml
- frontend/service.yaml

images:
- name: docker.io/ogabrielpereiraa/dystopian-news-backend
  newName: docker.io/ogabrielpereiraa/dystopian-news-backend
  newTag: 5b8cb29a920ea32afaeef35e2caa117e592f7c55
- name: docker.io/ogabrielpereiraa/dystopian-news-frontend
  newName: docker.io/ogabrielpereiraa/dystopian-news-frontend
  newTag: 5b8cb29a920ea32afaeef35e2caa117e592f7c55
