name: build-and-push

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - "frontend/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: backend/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dystopian-news-backend:${{ github.sha }}
          push: true
      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: frontend/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dystopian-news-frontend:${{ github.sha }}
          push: true
