name: build-and-push

on:
  # dispara automaticamente quando houver push na branch main
  # e algum arquivo dentro de backend/, frontend/ ou do próprio workflow mudar
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/**"

  # permite executar manualmente pelo botão "Run workflow" no GitHub
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    # constrói backend e frontend sem duplicar código
    strategy:
      matrix:
        include:
          - name: backend
            context: ./backend
            dockerfile: backend/Dockerfile
          - name: frontend
            context: ./frontend
            dockerfile: frontend/Dockerfile

    steps:
      # checkout do código
      - uses: actions/checkout@v4

      # habilita Buildx (cache + multiplataforma)
      - uses: docker/setup-buildx-action@v3

      # login no Docker Hub
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # build e push com DUAS tags: sha e latest
      - name: Build & push ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dystopian-news-${{ matrix.name }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/dystopian-news-${{ matrix.name }}:latest
