name: build-and-push

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - "frontend/**"

jobs:
  docker:
    runs-on: ubuntu-latest

    # evita duplicação usando matrix
    strategy:
      matrix:
        include:
          - name: backend
            context: ./backend
            dockerfile: backend/Dockerfile
          - name: frontend
            context: ./frontend
            dockerfile: frontend/Dockerfile

    steps:
      - uses: actions/checkout@v4

      # cria um builder Buildx (opcional, mas recomendado p/ cache & multiplataforma)
      - uses: docker/setup-buildx-action@v3

      # login no Docker Hub
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # build + push com DUAS tags (sha e latest)
      - name: Build & push ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dystopian-news-${{ matrix.name }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/dystopian-news-${{ matrix.name }}:latest
